// Code generated by gocli

package model2

import (
    "gocli/internal/model"
    "gocli/util/xsql/databese"
)

// CodeUserFromMaModel 用户分销来源表 模型
type CodeUserFromMaModel struct {
	model.DBModel
    
    ID int64 `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"` 
    UserID int64 `gorm:"column:user_id;type:int(11) unsigned;not null;comment:用户id" json:"user_id"` // 用户id
    ServerID int64 `gorm:"column:server_id;type:int(11);not null;comment:商家id" json:"server_id"` // 商家id
    MID string `gorm:"column:m_id;type:char(28);not null;comment:绑定的一二级" json:"m_id"` // 绑定的一二级
    CreatedAt int64 `gorm:"column:created_at;type:int(10) unsigned;not null;comment:创建时间" json:"created_at"` // 创建时间
}

// CodeUserFromMaModel 新用户分销来源表 模型实例
func NewCodeUserFromMaModel(db *databese.Engine) *CodeUserFromMaModel {
	return &CodeUserFromMaModel{DBModel: *model.NewDBModel(db, "zulin", "code_user_from_ma")}
}

