// Code generated by gocli

package tem

import (
    "gocli/internal/model"
    "gocli/util/xsql/databese"
)

// V3OrderModel COLUMNAR=1 订单表 模型
type V3OrderModel struct {
	model.DBModel
    
    OrderID int64 `gorm:"column:order_id;type:bigint(18);primaryKey;comment:订单id" json:"order_id"` // 订单id
    UserID int64 `gorm:"column:user_id;type:int(11);not null;comment:用户id" json:"user_id"` // 用户id
    ServerID int64 `gorm:"column:server_id;type:int(10) unsigned;not null;comment:租赁商id" json:"server_id"` // 租赁商id
    TimeStart int64 `gorm:"column:time_start;type:int(11);not null;comment:起租日期" json:"time_start"` // 起租日期
    TimeEnd int64 `gorm:"column:time_end;type:int(11);not null;comment:归还日期" json:"time_end"` // 归还日期
    ItemName *string `gorm:"column:item_name;type:varchar(255);comment:产品标题" json:"item_name"` // 产品标题
    Phone string `gorm:"column:phone;type:char(20);not null;comment:手机号码" json:"phone"` // 手机号码
    Category *string `gorm:"column:category;type:varchar(50);comment:商品分类code" json:"category"` // 商品分类code
    ItemID *string `gorm:"column:item_id;type:char(20);comment:产品id" json:"item_id"` // 产品id
    RentalMoney float64 `gorm:"column:rental_money;type:decimal(11,2) unsigned;not null;comment:订单总租金" json:"rental_money"` // 订单总租金
    RentalNeedPay *float64 `gorm:"column:rental_need_pay;type:decimal(11,2) unsigned;default:0.00;comment:需付租金" json:"rental_need_pay"` // 需付租金
    RentalHasPay *float64 `gorm:"column:rental_has_pay;type:decimal(11,2) unsigned;default:0.00;comment:已付租金" json:"rental_has_pay"` // 已付租金
    DepositMoney float64 `gorm:"column:deposit_money;type:decimal(11,2) unsigned;not null;comment:订单总押金" json:"deposit_money"` // 订单总押金
    DepositNeedPay *float64 `gorm:"column:deposit_need_pay;type:decimal(11,2) unsigned;default:0.00;comment:需冻结/支付押金（减后押金）" json:"deposit_need_pay"` // 需冻结/支付押金（减后押金）
    DepositHasPay *float64 `gorm:"column:deposit_has_pay;type:decimal(11,2) unsigned;default:0.00;comment:已冻结/支付押金" json:"deposit_has_pay"` // 已冻结/支付押金
    DepositPayType *int64 `gorm:"column:deposit_pay_type;type:tinyint(1) unsigned;default:1;comment:押金支付状态（1支付，2冻结）" json:"deposit_pay_type"` // 押金支付状态（1支付，2冻结）
    DepositHasRefund *float64 `gorm:"column:deposit_has_refund;type:decimal(11,2) unsigned;default:0.00;comment:解冻/退还" json:"deposit_has_refund"` // 解冻/退还
    BuyoutStatus *int64 `gorm:"column:buyout_status;type:tinyint(1) unsigned;default:1;comment:是否买断" json:"buyout_status"` // 是否买断
    FenqiNum *int64 `gorm:"column:fenqi_num;type:tinyint(1) unsigned;default:1;comment:分期期数" json:"fenqi_num"` // 分期期数
    Method string `gorm:"column:method;type:char(20);not null;comment:'pc','wap','live','alipay.mini','alipay.indi','app.v1','wx.mini','codewx.mini','alipay.code','alipay.merchant','alipay.trip','tt.mini','alipay.code.trip'" json:"method"` // 'pc','wap','live','alipay.mini','alipay.indi','app.v1','wx.mini','codewx.mini','alipay.code','alipay.merchant','alipay.trip','tt.mini','alipay.code.trip'
    OrderStatus *int64 `gorm:"column:order_status;type:tinyint(1) unsigned;default:1;comment:订单状态：1 待付款、2 待发货、3 待收货 4、待归还、5 归还中、6 已归还、7 待风控、10 等待服务中、13 正在租赁中(未确认)、14 正在租赁中(已确认转租金)、17：申请退押中、18 退款中、19 已买断、20 交易完成、21 订单关闭（用户）、22 订单关闭（租赁商）、23 订单关闭（系统）、24 订单关闭（已退款）、30 已删除" json:"order_status"` // 订单状态：1 待付款、2 待发货、3 待收货 4、待归还、5 归还中、6 已归还、7 待风控、10 等待服务中、13 正在租赁中(未确认)、14 正在租赁中(已确认转租金)、17：申请退押中、18 退款中、19 已买断、20 交易完成、21 订单关闭（用户）、22 订单关闭（租赁商）、23 订单关闭（系统）、24 订单关闭（已退款）、30 已删除
    PayStatus *int64 `gorm:"column:pay_status;type:tinyint(1) unsigned;default:1;comment:支付方式：支付方式：11 芝麻信用租代扣、12 支付宝免密代扣、13 支付宝免密代扣、25 花呗分期、26 预授权代扣、26 花呗月月付" json:"pay_status"` // 支付方式：支付方式：11 芝麻信用租代扣、12 支付宝免密代扣、13 支付宝免密代扣、25 花呗分期、26 预授权代扣、26 花呗月月付
    PayTime *int64 `gorm:"column:pay_time;type:int(11) unsigned;comment:付款时间" json:"pay_time"` // 付款时间
    CreatedBy *int64 `gorm:"column:created_by;type:tinyint(1) unsigned;default:1;comment:谁创建" json:"created_by"` // 谁创建
    CreatedAt int64 `gorm:"column:created_at;type:int(11) unsigned;not null;comment:创建时间" json:"created_at"` // 创建时间
    UpdatedAt int64 `gorm:"column:updated_at;type:int(11) unsigned;not null;comment:更新时间" json:"updated_at"` // 更新时间
    ThirdUserID string `gorm:"column:third_user_id;type:varchar(20);not null;comment:三方用户id" json:"third_user_id"` // 三方用户id
    ThirdType int64 `gorm:"column:third_type;type:tinyint(1) unsigned;not null;comment:三方类型：1（支付宝）" json:"third_type"` // 三方类型：1（支付宝）
    OriDepositMoney *float64 `gorm:"column:ori_deposit_money;type:decimal(11,2);not null;default:0.00;comment:产品押金" json:"ori_deposit_money"` // 产品押金
    Buyout *float64 `gorm:"column:buyout;type:decimal(11,2);not null;default:0.00;comment:买断价" json:"buyout"` // 买断价
    SkuName string `gorm:"column:sku_name;type:varchar(200);not null;comment:sku名称" json:"sku_name"` // sku名称
    ItemNum int64 `gorm:"column:item_num;type:int(11);not null;comment:产品数量" json:"item_num"` // 产品数量
    SchemeID int64 `gorm:"column:scheme_id;type:int(11) unsigned;not null;comment:套餐id" json:"scheme_id"` // 套餐id
    AutoBillSign int64 `gorm:"column:auto_bill_sign;type:tinyint(1);not null;comment:生成账单类型  0-手动  1-自动" json:"auto_bill_sign"` // 生成账单类型  0-手动  1-自动
}

// V3OrderModel 新COLUMNAR=1 订单表 模型实例
func NewV3OrderModel(db *databese.Engine) *V3OrderModel {
	return &V3OrderModel{DBModel: *model.NewDBModel(db, "zulin", "v3_order")}
}

